logging:
  level:
    org.springframework: INFO
    ma.gov.pfe: DEBUG
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/users-dev
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console